/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.13/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    java
    id("com.gradleup.shadow") version "8.3.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven("https://repo.pgm.fyi/snapshots") // Sportpaper & other pgm-specific stuff
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.jda)
    implementation(libs.logback)
    compileOnly(libs.paper.intersect)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}